services:
  web:
    build: .
    image: chillsharp-www
    container_name: chillsharp-www
    restart: always
    volumes:
      - "./:/usr/share/nginx/html"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chillsharp-static.rule=Host(`chillsharp.dev`)"
      - "traefik.http.routers.chillsharp-static.entrypoints=websecure"
      - "traefik.http.routers.chillsharp-static.tls=true"
      - "traefik.http.routers.chillsharp-static.tls.certresolver=letsencrypt"
      - "traefik.http.services.chillsharp-static.loadbalancer.server.port=80"
    networks:
      - default

networks:
  default:
    external:
      name: traefik-net
